apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vqsn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vqsn
    app.kubernetes.io/part-of: ci1t-830-0065-app
  name: devfile-sample-vqsn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vqsn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vqsn
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0065-tenant/ci1t-830-0065-app/devfile-sample-vqsn@sha256:f4b662eafd7ca90fa99855a83a1eee388b91b02bd43c1768f148f5155828ea10
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
